### ISSUE TITLE
Getting E/SpeechService: converse error: io.grpc.StatusRuntimeException: UNAUTHENTICATED

### ISSUE THREAD

**Issue by tanishkgupta** [hsavaliya/GoogleAssistantSDK#1]
Hi Hetal,

I am getting errors even after replacing the credentials.json with my own, does this setup works? :

E/SpeechService: converse error:
    io.grpc.StatusRuntimeException: UNAUTHENTICATED
        at io.grpc.Status.asRuntimeException(Status.java:539)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:392)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:422)
        at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:74)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:508)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:425)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:540)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
        at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
     Caused by: com.google.api.client.http.HttpResponseException: 400 Bad Request
    {
      "error": "invalid_grant",
      "error_description": "Bad Request"
    }

**Comment by tanishkgupta** [comment]
It's working now!
